// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv6rVbqlYD__l_eFrNvvIduKn1XReXuMw',
    appId: '1:57470927439:web:8dff272ee7acaf1eb5603a',
    messagingSenderId: '57470927439',
    projectId: 'sio-app-db',
    authDomain: 'sio-app-db.firebaseapp.com',
    storageBucket: 'sio-app-db.firebasestorage.app',
    measurementId: 'G-3WFJHZHT0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrhItpIcRAO_6-rbUvM2z7gmzJlD79JaM',
    appId: '1:57470927439:android:e6816772002bc8ffb5603a',
    messagingSenderId: '57470927439',
    projectId: 'sio-app-db',
    storageBucket: 'sio-app-db.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv6rVbqlYD__l_eFrNvvIduKn1XReXuMw',
    appId: '1:57470927439:web:8f8490fc55233a3cb5603a',
    messagingSenderId: '57470927439',
    projectId: 'sio-app-db',
    authDomain: 'sio-app-db.firebaseapp.com',
    storageBucket: 'sio-app-db.firebasestorage.app',
    measurementId: 'G-PG08MQKJ3S',
  );
}
